### ISSUE TITLE
Linux - Compiling as 32bit or 64bit? Can't Compile...

### ISSUE THREAD

**Issue by ghost** [reicast/reicast-emulator#918]
Hi,

Trying to compile on Slackware 14.1 x86_64 multilib and it's failing.

Below I tried to compile it 32bit & 64bit...

**Comment by Geyup** [comment]
Sorry I was all excited seeing a Dreamcast emulator, and I was paying attention to the version dates, and I downloaded the r7, which gave me the above errors.

I just cloned the lastest from git today and I now have a different error with this;


../../core/linux/context.cpp: In function ‘void context_segfault(rei_host_context_t*, void*, bool)’:
../../core/linux/context.cpp:64:33: error: ‘REG_RIP’ was not declared in this scope
  bicopy(reictx->pc, MCTX(.gregs[REG_RIP]), to_segfault);
                                 ^
../../core/linux/context.cpp:19:62: note: in definition of macro ‘MCTX’
 #define MCTX(p) (((ucontext_t *)(segfault_ctx))->uc_mcontext p)
                                                              ^
make: *** [obj-dreamcast-x64-sse4_1/linux/context.build_obj] Error 1

**Comment by Geyup** [comment]
SORRY I don't know where I was reading this was to be compiled as 32bit...

If I compile it as 64bit this is what I get;

mkdir -p obj-dreamcast-x64-sse4_1/rend/gles/
g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -DTARGET_SOFTREND ../../core/rend/gles/gldraw.cpp -o obj-dreamcast-x64-sse4_1/rend/gles/gldraw.build_obj
../../core/rend/gles/gldraw.cpp: In function ‘void DrawSorted()’:
../../core/rend/gles/gldraw.cpp:779:104: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
      glDrawElements(GL_TRIANGLES, pidx_sort[p].count, GL_UNSIGNED_SHORT, (GLvoid*)(2*pidx_sort[p].first)); glCheck();
                                                                                                        ^
../../core/rend/gles/gldraw.cpp: In instantiation of ‘void DrawList(const List<PolyParam>&) [with unsigned int Type = 0u; bool SortingEnabled = false]’:
../../core/rend/gles/gldraw.cpp:1108:55:   required from here
../../core/rend/gles/gldraw.cpp:281:98: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    glDrawElements(GL_TRIANGLE_STRIP, params->count, GL_UNSIGNED_SHORT, (GLvoid*)(2*params->first)); glCheck();
                                                                                                  ^
../../core/rend/gles/gldraw.cpp: In instantiation of ‘void DrawList(const List<PolyParam>&) [with unsigned int Type = 4u; bool SortingEnabled = false]’:
../../core/rend/gles/gldraw.cpp:1115:62:   required from here
../../core/rend/gles/gldraw.cpp:281:98: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
../../core/rend/gles/gldraw.cpp: In instantiation of ‘void DrawList(const List<PolyParam>&) [with unsigned int Type = 2u; bool SortingEnabled = false]’:
../../core/rend/gles/gldraw.cpp:1133:62:   required from here
../../core/rend/gles/gldraw.cpp:281:98: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
mkdir -p obj-dreamcast-x64-sse4_1/rend/gles/
g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -DTARGET_SOFTREND ../../core/rend/gles/gles.cpp -o obj-dreamcast-x64-sse4_1/rend/gles/gles.build_obj
../../core/rend/gles/gles.cpp:221:0: warning: "vary" redefined
 #define vary "in"
 ^
../../core/rend/gles/gles.cpp:67:0: note: this is the location of the previous definition
 #define vary "out"
 ^
mkdir -p obj-dreamcast-x64-sse4_1/rend/soft/
g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -DTARGET_SOFTREND ../../core/rend/soft/softrend.cpp -o obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj
../../core/rend/soft/softrend.cpp: In member function ‘__m128 softrend::shuffle_pixel(__m128)’:
../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type ‘__m128i {aka __vector(2) long long int}’ to type ‘__m128& {aka __vector(4) float&}’
   return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1, 0)));
                                                                             ^
make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1

**Comment by sairuk** [comment]
I experienced this error only during compilation on 64bit debian/cmake version 3.2.2

` ../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type ‘__m128i {aka __vector(2) long long int}’ to type ‘__m128& {aka __vector(4) float&}’`

managed to complete the compilation by removing the first ampersand from line 1167 in question, as per below, couldn't tell you what its doing but it compiled fine after this.

`return (__m128)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1,0)));`

**Comment by ProfessorKaos64** [comment]
Same here:

Build log: http://sprunge.us/SIWD

**Comment by ProfessorKaos64** [comment]
Fixed with PR #914 for me. See [this other issue](https://github.com/reicast/reicast-emulator/issues/883#issuecomment-231384086). I have not testing the application, but it builds fine now. Debian 8 system. It would fail out on a low ram / swap space VPS, but on my main desktop (16 GB RAM) it was fine.

**Comment by mckaygerhard** [comment]
fail on low ram? seems more cheap and better buy a old dreamcast in amazon! non-sense!

**Comment by ProfessorKaos64** [comment]
@mckaygerhard , building with the lowest spec VPS from digital ocean isn't without it's problems. I am only guessing low resources, since the fail out on gcc usually indicates that. I made a goof myself, I forgot to actually rehook the swap when I destroyed and rebuilt the image recently. I do have my own Dreamcast, and I love* it. I build community packages for SteamOS.

**Comment by LoungeKatt** [comment]
You could buy a Dreamcast on Amazon, but using the emulator implies you own one and are not illegally obtaining the BIOS. You could then buy an older TV to support the VGA connections and give up a few cubic feet of space to run it. You could buy 4 controllers and give up any hope of network functionality. You could even buy a restoration kit for any scratches on your games to keep them running. You can keep doing this every time a console burns out, the TV dies, a controller fails, or a disk is damaged.

... Or you could use reicast and only have to worry about getting ANY supported device, even one with another primary use.

**Comment by TheBurgerGuy** [comment]
True That

**Comment by Geyup** [comment]
Or you could use Retroarch, development seems more active for Dreamcast...

But let's stay on Topic, Geeks know how to Surf! :)

**Comment by mckaygerhard** [comment]
!retroarch seems more cheat in terms of resources... and exits adaptors for vga... i tested build in jeesie! too much resource

seems retroarchhave two modules for dreamcast and lxdream also still works... why recent develops are resourceexpensive today? suppost now with more tech mustbe more light!

**Comment by skmp** [comment]
Retroarch is actually using reicast as a dreamcast core, with some minor
modifications. I'll try to get the building issues addressed over the next
weeks :)

>

**Comment by skmp** [comment]
This should no longer be an issue. Also, such discussion belongs to http://forum.reicast.com from now on. Thanks :)

**Comment by mdeguzis** [comment]
Discussion that you can't compile? If that's the case, you  might as well remove the issues section or be string on the guidelines for submission.

**Comment by skmp** [comment]
This issue tracking is for internal team coordination and tracking- it is not the best place to have general support for people that are getting started. 

De cluttering the issues and making sure only actionable and relevant to the team issues are here makes everyone more productive and happy, imo. 

Dcemulation has a lot of developers around so it shouldn’t be a bad place to have these discussions.

Don’t you agree?
